<?php

namespace App\DTOs\StudentProfile;

use App\Models\StudentProfile;

class StudentProfileUpdateData
{
    public function __construct(
        public readonly StudentProfile $profile,
        public readonly string $userId,
        public readonly string $name,
        public readonly ?string $email,
        public readonly ?string $phone,
        public readonly ?string $nrc,
        public readonly ?string $password,
        public readonly bool $isActive,
        public readonly string $studentIdentifier,
        public readonly ?string $startingGradeAtSchool,
        public readonly ?string $currentGrade,
        public readonly ?string $currentClass,
        public readonly ?string $guardianTeacher,
        public readonly ?string $assistantTeacher,
        public readonly ?string $dateOfJoining,
        public readonly ?string $gender,
        public readonly ?string $ethnicity,
        public readonly ?string $religious,
        public readonly ?string $dob,
        public readonly ?string $previousSchoolName,
        public readonly ?string $previousSchoolAddress,
        public readonly ?string $address,
        public readonly ?string $fatherName,
        public readonly ?string $fatherNrc,
        public readonly ?string $fatherPhoneNo,
        public readonly ?string $fatherOccupation,
        public readonly ?string $motherName,
        public readonly ?string $motherNrc,
        public readonly ?string $motherPhoneNo,
        public readonly ?string $motherOccupation,
        public readonly ?string $emergencyContactPhoneNo,
        public readonly ?string $inSchoolRelativeName,
        public readonly ?string $inSchoolRelativeGrade,
        public readonly ?string $inSchoolRelativeRelationship,
        public readonly ?string $bloodType,
        public readonly ?float $weight,
        public readonly ?float $height,
        public readonly ?string $medicineAllergy,
        public readonly ?string $foodAllergy,
        public readonly ?string $medicalDirectory,
        public readonly ?string $photoPath,
        public readonly ?string $classId,
        public readonly ?string $gradeId,
        public readonly ?string $status,
    ) {}

    public static function from(StudentProfile $profile, array $validated): self
    {
        return new self(
            profile: $profile,
            userId: $validated['user_id'],
            name: $validated['name'],
            email: $validated['email'] ?? null,
            phone: $validated['phone'] ?? null,
            nrc: $validated['nrc'] ?? null,
            password: $validated['password'] ?? null,
            isActive: (bool) ($validated['is_active'] ?? true),
            studentIdentifier: $validated['student_identifier'],
            startingGradeAtSchool: $validated['starting_grade_at_school'] ?? null,
            currentGrade: $validated['current_grade'] ?? null,
            currentClass: $validated['current_class'] ?? null,
            guardianTeacher: $validated['guardian_teacher'] ?? null,
            assistantTeacher: $validated['assistant_teacher'] ?? null,
            dateOfJoining: $validated['date_of_joining'] ?? null,
            gender: $validated['gender'] ?? null,
            ethnicity: $validated['ethnicity'] ?? null,
            religious: $validated['religious'] ?? null,
            dob: $validated['dob'] ?? null,
            previousSchoolName: $validated['previous_school_name'] ?? null,
            previousSchoolAddress: $validated['previous_school_address'] ?? null,
            address: $validated['address'] ?? null,
            fatherName: $validated['father_name'] ?? null,
            fatherNrc: $validated['father_nrc'] ?? null,
            fatherPhoneNo: $validated['father_phone_no'] ?? null,
            fatherOccupation: $validated['father_occupation'] ?? null,
            motherName: $validated['mother_name'] ?? null,
            motherNrc: $validated['mother_nrc'] ?? null,
            motherPhoneNo: $validated['mother_phone_no'] ?? null,
            motherOccupation: $validated['mother_occupation'] ?? null,
            emergencyContactPhoneNo: $validated['emergency_contact_phone_no'] ?? null,
            inSchoolRelativeName: $validated['in_school_relative_name'] ?? null,
            inSchoolRelativeGrade: $validated['in_school_relative_grade'] ?? null,
            inSchoolRelativeRelationship: $validated['in_school_relative_relationship'] ?? null,
            bloodType: $validated['blood_type'] ?? null,
            weight: isset($validated['weight']) ? (float) $validated['weight'] : null,
            height: isset($validated['height']) ? (float) $validated['height'] : null,
            medicineAllergy: $validated['medicine_allergy'] ?? null,
            foodAllergy: $validated['food_allergy'] ?? null,
            medicalDirectory: $validated['medical_directory'] ?? null,
            photoPath: $validated['photo_path'] ?? null,
            classId: $validated['class_id'] ?? null,
            gradeId: $validated['grade_id'] ?? null,
            status: $validated['status'] ?? 'active',
        );
    }
}
